name: CD workflow

on:
  push:
    branches:
      - develop

jobs:
  cd:
    runs-on: ubuntu-latest
    name: Build and publish docker
    steps:
      - uses: actions/checkout@v5
      - name: Login docker
        run: docker login -u ${{ vars.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker
        run: docker build . -t chuotcona123/training:${{ github.sha }}
      - name: Docker push
        run: docker push chuotcona123/training:${{ github.sha }}
